{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.namespace }}-alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - containerPort: 9093
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            # Writable storage for alertmanager data
            - name: storage
              mountPath: /alertmanager
            # Alertmanager 설정
            - name: config
              mountPath: /etc/alertmanager

            # Slack Webhook Secret
            - name: secrets
              mountPath: /etc/alertmanager/secrets
              readOnly: true
      volumes:
        - name: storage
          emptyDir: {}
        - name: config
          configMap:
            name: {{ .Values.global.namespace }}-alertmanager-config

        # Slack Webhook Secret
        - name: secrets
          secret:
            secretName: {{ .Release.Name }}-alertmanager-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.namespace }}-alertmanager
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
{{- end }}
