apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.namespace }}-grafana-config
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    domain = grafana.monitoring.softwarecampus.co.kr
    root_url = https://grafana.monitoring.softwarecampus.co.kr/
    serve_from_sub_path = false
    enforce_domain = false

    [security]
    cookie_secure = true
