{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.namespace }}-grafana
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.namespace }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Values.global.namespace }}-grafana
        cluster: {{ .Values.global.namespace }}
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - containerPort: 3000
{{- if and .Values.grafana.ingress.enabled .Values.grafana.ingress.host }}
{{- end }}

          volumeMounts:
            # Grafana config
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini

            # Datasources
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources

            # Dashboards provisioning (디렉터리로!)
            - name: dashboards-provisioning
              mountPath: /etc/grafana/provisioning/dashboards

            # Dashboards JSON (실제 파일 위치)
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            
      volumes:
        # Grafana config
        - name: grafana-config
          configMap:
            name: {{ .Values.global.namespace }}-grafana-config

        # Datasources
        - name: datasources
          configMap:
            name: {{ .Values.global.namespace }}-grafana-datasources

        # Dashboards provisioning yaml
        - name: dashboards-provisioning
          configMap:
            name: {{ .Values.global.namespace }}-grafana-dashboard-provisioning

        # Dashboards JSON
        - name: dashboards
          configMap:
            name: {{ .Values.global.namespace }}-grafana-dashboards
{{- end }}
