{{- if and .Values.grafana.enabled .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.namespace }}-grafana
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ default "internet-facing" .Values.grafana.ingress.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: {{ default "ip" .Values.grafana.ingress.targetType | quote }}
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-path: "/api/health"
    alb.ingress.kubernetes.io/success-codes: "200"

{{- if ne .Values.grafana.ingress.certificateArn "" }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
{{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
{{- end }}


{{- if ne .Values.grafana.ingress.certificateArn "" }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.grafana.ingress.certificateArn | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
{{- end }}

spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.grafana.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.namespace }}-grafana
                port:
                  number: {{ .Values.grafana.service.port }}
{{- end }}
