{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.namespace }}-grafana
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.namespace }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Values.global.namespace }}-grafana
        cluster: {{ .Values.global.namespace }}
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - containerPort: 3000
          volumeMounts:
            # Datasources
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources

            # Dashboards provisioning yaml
            - name: dashboards-provisioning
              mountPath: /etc/grafana/provisioning/dashboards.yaml
              subPath: dashboards.yaml

            # Dashboards JSON files
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards

      volumes:
        # Datasources
        - name: datasources
          configMap:
            name: {{ .Values.global.namespace }}-grafana-datasources

        # Dashboards provisioning
        - name: dashboards-provisioning
          configMap:
            name: {{ .Values.global.namespace }}-grafana-dashboard-provisioning

        # Dashboards JSON
        - name: dashboards
          configMap:
            name: {{ .Values.global.namespace }}-grafana-dashboards
{{- end }}
