{{- if .Values.otelCollector.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-otel-collector
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.namespace }}-otel-collector
spec:
  replicas: {{ .Values.otelCollector.replicas | default 2 }}
  selector:
    matchLabels:
      app: {{ .Values.global.namespace }}-otel-collector
  template:
    metadata:
      labels:
        app: {{ .Values.global.namespace }}-otel-collector
        cluster: {{ .Values.global.namespace }}
    spec:
      serviceAccountName: {{ .Values.global.namespace }}-otel-collector
      containers:
          - name: otel-collector
            image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
            imagePullPolicy: "{{ .Values.otelCollector.image.pullPolicy }}"
            args:
              - "--config=/etc/otel-collector/otel-collector.yml"
            ports:
              - containerPort: 4317  # gRPC
                name: otlp-grpc
              - containerPort: 4318  # HTTP
                name: otlp-http
              - containerPort: 8889  # HTTP
                name: prometheus
            volumeMounts:
              - name: config
                mountPath: /etc/otel-collector
                readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Values.global.namespace }}-otel-collector-config
{{- end }}
