{{- if .Values.configMaps.otelCollectorConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.namespace }}-otel-collector-config
data:
  otel-collector.yml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:

    processors:
      batch:
        timeout: 5s                  # 최대 5초동안 모아서 전송
        send_batch_size: 1024        # 최대 1024개의 로그를 모아서 전송
      
      # labels 처리를 위한 processor 추가
      resource:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: service.name, deployment.environment

    exporters:
      loki:
        endpoint: http://{{ .Values.global.namespace }}-loki:3100/loki/api/v1/push
      
      # prometheus exporter - OTel Collector에서 metrics를 수집하여 Prometheus로 전송
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: otel
        const_labels:
          cluster: {{ .Values.global.namespace }}

      {{- if .Values.otelCollector.debug }}
      logging:
        loglevel: info
      {{- end }} 

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters:
            {{- if .Values.otelCollector.debug }}
            - logging
            {{- end }}
            - loki
        
        # 메트릭 파이프라인 - 애플리케이션 메트릭을 prometheus로 전송
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters:
            - prometheus
{{- end }} 