{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.namespace }}-otel-collector
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.otelCollector.labels.app }}
spec:
  selector:
    app: {{ .Values.otelCollector.labels.app }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: telemetry
      port: 8888
      targetPort: 8888
    - name: prometheus-metrics
      port: 8889
      targetPort: 8889
{{- end }}

