{{- if .Values.configMaps.prometheusRules.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.namespace }}-prometheus-rules
  labels:
    prometheus: rules
data:
  rules.yml: |
    groups:
      - name: kubernetes-alerts
        rules:
          - alert: PodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Pod CrashLoop 발생"
              description: "{{`{{ $labels.pod }}`}} 가 반복 재시작 중"

          - alert: PodNotReady
            expr: kube_pod_status_ready{condition="true"} == 0
            for: 3m
            labels:
              severity: critical
            annotations:
              summary: "Pod Ready 아님"
              description: "{{`{{ $labels.pod }}`}} 이 Ready 상태가 아님"
{{- end }}
