{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.namespace }}-prometheus
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.namespace }}-prometheus
  template:
    metadata:
      labels:
        app: {{ .Values.global.namespace }}-prometheus
        cluster: {{ .Values.global.namespace }}
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
            - name: storage
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: {{ .Values.global.namespace }}-prometheus-config
        - name: storage
          emptyDir: {}    # 개발 환경에서만 사용 - pod 재시작될 때마다 데이터 날아감
{{- end }}

