{{- if .Values.configMaps.prometheusRules.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.namespace }}-prometheus-rules
  labels:
    app: prometheus
data:
  swcampus.rules.yml: |
    groups:
    - name: swcampus-k8s-basic
      rules:
      # Pod 재시작 과다 (15분에 3회 초과)
      - alert: PodRestarting
        expr: increase(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[15m]) > 3
        for: 2m
        labels:
          severity: warning
          env: {{ .Values.global.env | default "dev" }}
        annotations:
          summary: "Pod restarting frequently"
          description: "A pod restarted more than 3 times in the last 15 minutes."

      # CrashLoopBackOff 상태
      - alert: PodCrashLoopBackOff
        expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", job="kube-state-metrics"} == 1
        for: 2m
        labels:
          severity: critical
          env: {{ .Values.global.env | default "dev" }}
        annotations:
          summary: "CrashLoopBackOff detected"
          description: "A pod is in CrashLoopBackOff state."

      # Node Ready 상태 아님
      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready", status="true", job="kube-state-metrics"} == 0
        for: 5m
        labels:
          severity: critical
          env: {{ .Values.global.env | default "dev" }}
        annotations:
          summary: "Node not ready"
          description: "A node has been not Ready for more than 5 minutes."

    - name: swcampus-resource
      rules:
      # 컨테이너 CPU 과다
      - alert: HighContainerCPU
        expr: sum by (namespace,pod) (
                rate(container_cpu_usage_seconds_total{container!="",pod!=""}[5m])
              ) > 1
        for: 5m
        labels:
          severity: warning
          env: {{ .Values.global.env | default "dev" }}
        annotations:
          summary: "High container CPU usage"
          description: "CPU usage is high for a container."

      # 컨테이너 메모리 과다
      - alert: HighContainerMemory
        expr: sum by (namespace,pod) (
                container_memory_working_set_bytes{container!="",pod!=""}
              ) > 1500000000
        for: 5m
        labels:
          severity: warning
          env: {{ .Values.global.env | default "dev" }}
        annotations:
          summary: "High container memory usage"
          description: "Memory working set is high for a container."
{{- end }}
