{{- if .Values.tempo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.namespace }}-tempo
spec:
  replicas: {{ .Values.tempo.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.namespace }}-tempo
  template:
    metadata:
      labels:
        app: {{ .Values.global.namespace }}-tempo
        cluster: {{ .Values.global.namespace }}
    spec:
      containers:
        - name: tempo
          image: "{{ .Values.tempo.image.repository }}:{{ .Values.tempo.image.tag }}"
          imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
          ports:
            - containerPort: 3200
{{- end }}

