apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-grafana
  namespace: monitoring-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-grafana
  template:
    metadata:
      labels:
        app: dev-grafana
        cluster: dev
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: datasources
          configMap:
            name: dev-grafana-datasources
