global:
  namespace: develop
  imagePullSecrets:
    - ghcr-secret

server:
  enabled: true
  replicas: 2
  image:
    repository: ghcr.io/sw-campus/sw-campus-server
    tag: "develop"
    pullPolicy: IfNotPresent

  # ✅ ConfigMap: profile 같은 비민감 정보만
  configMap:
    name: sw-campus-server-config-develop
    data:
      SPRING_PROFILES_ACTIVE: dev

  # ✅ Secret: DB 정보만
  secret:
    enabled: true
    name: swcampus-db-dev   # ← DB Secret 이름

client:
  enabled: true
  replicas: 2
  image:
    repository: ghcr.io/sw-campus/sw-campus-client
    tag: "develop"
    pullPolicy: IfNotPresent
  configMap:
    name: sw-campus-client-config

ai:
  enabled: true
  replicas: 2
  image:
    repository: ghcr.io/sw-campus/sw-campus-ai
    tag: "develop"
    pullPolicy: IfNotPresent

configMaps:
  server:
    enabled: true
  client:
    enabled: true
