apiVersion: v1
kind: Service
metadata:
  name: sw-campus-client
  namespace: default
  labels:
    app: sw-campus-client
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: sw-campus-client

