apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: release

resources:
  # ===== AI =====
  - ai/deployment.yaml
  - ai/service.yaml

  # ===== CLIENT =====
  - client/deployment.yaml
  - client/service.yaml

  # ===== SERVER =====
  - server/deployment.yaml
  - server/service.yaml
  - server/configmap.yaml

  # ===== CONFIG =====
  - config/client-configmap.yaml
  - config/server-configmap.yaml

  # ===== DATABASE =====
  - database/postgres-external-service.yaml
