# Release environment values
global:
  namespace: release
  imagePullSecrets:
    - ghcr-secret

server:
  enabled: true
  replicas: 2
  image:
    repository: ghcr.io/sw-campus/sw-campus-server
    tag: v1.0.0
    pullPolicy: IfNotPresent
  configMap:
    name: sw-campus-server-config
  secret:
    enabled: true
    name: sw-campus-server-secret

client:
  enabled: true
  replicas: 2
  image:
    repository: ghcr.io/sw-campus/sw-campus-client
    tag: v1.0.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 30081
  configMap:
    name: sw-campus-client-config

ai:
  enabled: true
  replicas: 2
  image:
    repository: ghcr.io/sw-campus/sw-campus-ai
    tag: v1.0.0
    pullPolicy: IfNotPresent

database:
  enabled: true
  externalService:
    name: postgres-service
    externalName: ip-172-16-2-174.ap-northeast-2.compute.internal
    port: 5432

configMaps:
  server:
    enabled: true
  client:
    enabled: true

