global:
  namespace: release
  imagePullSecrets:
    - ghcr-secret

server:
  enabled: true
  replicas: 1
  image:
    repository: ghcr.io/sw-campus/sw-campus-server
    tag: v1.0.0
    pullPolicy: IfNotPresent

  # ✅ profile = release
  configMap:
    name: sw-campus-server-config-release
    data:
      SPRING_PROFILES_ACTIVE: release

  # ✅ DB Secret = release
  secret:
    enabled: true
    name: swcampus-db-release

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
