apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-otel-collector
  namespace: monitoring-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-otel-collector
  template:
    metadata:
      labels:
        app: prod-otel-collector
        cluster: prod
    spec:
      serviceAccountName: prod-otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.96.0
