apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # application configs
  - client-configmap.yaml
  - server-configmap.yaml

  # observability configs
#  - loki-config.yaml
#  - promtail-config.yaml
#  - prometheus-config.yaml
#  - tempo-config.yaml
#  - otel-collector-config.yaml
