apiVersion: v1
kind: ConfigMap
metadata:
  name: sw-campus-server-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "staging"
  
  # Redis
  REDIS_HOST: "CHANGE_ME"
  REDIS_PORT: "6379"
  
  # Mail
  MAIL_HOST: "CHANGE_ME"
  MAIL_PORT: "587"
  
  # AWS
  AWS_REGION: "ap-northeast-2"
  S3_PUBLIC_BUCKET_NAME: "CHANGE_ME"
  S3_PRIVATE_BUCKET_NAME: "CHANGE_ME"
  
  # OAuth Redirect URIs
  GOOGLE_REDIRECT_URI: "CHANGE_ME"
  GITHUB_REDIRECT_URI: "CHANGE_ME"
  
  # OCR Server
  OCR_SERVER_URL: "CHANGE_ME"

