apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client/deployment.yaml
  - client/service.yaml
  - server/deployment.yaml
  - server/service.yaml
  - config/client-configmap.yaml
  - config/server-configmap.yaml
  - database/postgres-external-service.yaml

