# Default values for sw-campus

# =========================
# Global settings
# =========================
global:
  namespace: release
  imagePullSecrets:
    - name: ghcr-secret

# =========================
# Server settings
# =========================
server:
  enabled: true
  replicas: 2

  image:
    repository: ghcr.io/sw-campus/sw-campus-server
    tag: release
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  configMap:
    name: sw-campus-server-config-release
    data:
      cors.allowed-origins: https://www.softwarecampus.co.kr,https://softwarecampus.co.kr

  serverSecret:
    enabled: true
    name: sw-campus-server-secret-release

  dbsecret:
    enabled: true
    name: sw-campus-db-secret-release

  awsSecret:
    enabled: true
    name: sw-campus-aws-secret-release

  oauth2Secret:
    enabled: true
    name: sw-campus-oauth-secret-release

  env:
    - name: SPRING_BATCH_JOB_ENABLED
      value: "false"
    - name: SPRING_BATCH_JOB_NAMES
      value: "NONE"
    - name: JAVA_TOOL_OPTIONS
      value: "-Djava.net.preferIPv4Stack=true"


  resources:
    requests:
      cpu: 300m
      memory: 768Mi
    limits:
      cpu: 1000m
      memory: 1.5Gi

  livenessProbe:
    httpGet:
      path: /internal/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10

# =========================
# Client settings
# =========================
client:
  enabled: true
  replicas: 2

  image:
    repository: ghcr.io/sw-campus/sw-campus-client
    tag: develop
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000

  configMap:
    name: sw-campus-client-config

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi


# =========================
# AI settings
# =========================
ai:
  enabled: true 
  replicas: 2

  image:
    repository: ghcr.io/sw-campus/sw-campus-ai
    tag: develop
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8000

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi


# =========================
# Database configuration
# =========================
database:
  enabled: true
  externalService:
    name: postgres-service
    externalName: postgres
    port: 5432

# =========================
# Ingress settings
# =========================
ingress:
  enabled: true
  className: alb

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/healthcheck-path: /health
    # alb.ingress.kubernetes.io/healthcheck-port: "8080"
    # alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: "3000"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "10"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"



  certificateArn: ""

  hosts:
    - host: softwarecampus.co.kr
      paths:
        - path: /actuator
          pathType: Prefix
          service:
            name: sw-campus-server
            port: 8080
        - path: /
          pathType: Prefix
          service:
            name: sw-campus-client
            port: 3000
        - path: /api
          pathType: Prefix
          service:
            name: sw-campus-server
            port: 8080

    - host: www.softwarecampus.co.kr
      paths:
        - path: /actuator
          pathType: Prefix
          service:
            name: sw-campus-server
            port: 8080
        - path: /
          pathType: Prefix
          service:
            name: sw-campus-client
            port: 3000
        - path: /api
          pathType: Prefix
          service:
            name: sw-campus-server
            port: 8080

            

# =========================
# ConfigMaps
# =========================
configMaps:
  server:
    enabled: true
  client:
    enabled: true
