apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - grafana-deployment.yaml
  - grafana-datasources.yaml
  - grafana-dashboard-provisioning.yaml
  - grafana-dashboards.yaml

  - prometheus-deployment.yaml

  - loki-deployment.yaml
  - promtail-deployment.yaml

  - tempo-deployment.yaml

  - otel-collector-rbac.yaml
  - otel-collector-deployment.yaml
