apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-grafana-datasources
  namespace: monitoring-prod
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prod-prometheus.monitoring-prod:9090
        isDefault: true

      - name: Loki
        type: loki
        access: proxy
        url: http://prod-loki.monitoring-prod:3100

      - name: Tempo
        type: tempo
        access: proxy
        url: http://prod-tempo.monitoring-prod:3200
