apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sw-campus-develop-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sw-campus/sw-campus-manifest
    targetRevision: develop
    path: k8s/charts/monitoring
    helm:
      valueFiles:
        - ../../environments/develop-monitoring/values.yaml
      parameters:
        - name: monitoring.targetNamespace
          value: develop

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
