apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sw-campus-release
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sw-campus/sw-campus-manifest
    targetRevision: release
    path: k8s/charts/sw-campus
    helm:
      valueFiles:
        - ../../environments/release/values.yaml

  destination:
    server: eks-prod
    namespace: release

  # Ingress는 AWS 콘솔에서 수동 관리하므로 ArgoCD가 무시하도록 설정
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /metadata/annotations
        - /spec

  syncPolicy:
    automated:
      prune: false  # Ingress 삭제 방지!
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
