apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sw-campus-monitoring-release
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sw-campus/sw-campus-manifest
    targetRevision: release
    path: k8s/charts/monitoring
    helm:
      valueFiles:
        - ../../environments/release-monitoring/values.yaml
      parameters:
        - name: monitoring.targetNamespace
          value: release

  destination:
    server: eks-prod
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
