apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sw-campus-release
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sw-campus/sw-campus-manifest
    targetRevision: release
    path: k8s/charts/sw-campus
    helm:
      valueFiles:
        - ../../environments/release/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: release

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
