apiVersion: v1
kind: ConfigMap
metadata:
  name: sw-campus-server-config
  namespace: default
data:
  application.yml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true

      data:
        redis:
          host: ${REDIS_HOST}
          port: ${REDIS_PORT}

    aws:
      region: ${AWS_REGION}

    oauth:
      google:
        redirect-uri: ${GOOGLE_REDIRECT_URI}
      github:
        redirect-uri: ${GITHUB_REDIRECT_URI}

    mail:
      host: ${MAIL_HOST}
      port: ${MAIL_PORT}

    s3:
      public-bucket: ${S3_PUBLIC_BUCKET_NAME}
      private-bucket: ${S3_PRIVATE_BUCKET_NAME}

    ocr:
      server-url: ${OCR_SERVER_URL}
