apiVersion: v1
data:
  DB_PASSWORD: MTExMQ==
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTcyLjMwLjEuODM6NTQzMi9zd2NhbXB1cw==
  DB_USERNAME: cG9zdGdyZXM=
  JWT_SECRET: UjVxNkpSNHdDTTZDQ3N2V3VRN3dNK2tLT2NhYmNhWUNDRjhwT0lVc21xVT0=
kind: Secret
metadata:
  creationTimestamp: "2025-12-16T03:14:02Z"
  name: sw-campus-server-secret
  namespace: default
  resourceVersion: "540192"
  uid: ed3e8bd9-d3c7-4852-b94b-9bdec5d840db
type: Opaque