apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sw-campus-develop
  namespace: argocd  # ArgoCD가 설치된 네임스페이스
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/sw-campus/sw-campus-manifest  # Manifest 레포 URL
    targetRevision: develop  # develop 브랜치 감시
    path: k8s/env/develop  # k8s 디렉토리 경로
    kustomize: {}
    
  destination:
    server: https://kubernetes.default.svc  # 리눅스 서버 쿠버네티스
    namespace: default
    
  syncPolicy:
    automated:
      prune: true  # 삭제된 리소스 자동 정리
      selfHeal: true  # 수동 변경사항 자동 복구
    syncOptions:
      - CreateNamespace=true  # 네임스페이스 자동 생성

