apiVersion: v1
kind: Service
metadata:
  name: sw-campus-server
  labels:
    app: sw-campus-server
spec:
  type: ClusterIP
  selector:
    app: sw-campus-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
