apiVersion: apps/v1
kind: Deployment
metadata:
  name: sw-campus-ai
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw-campus-ai
  template:
    metadata:
      labels:
        app: sw-campus-ai
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ai
          image: image: ghcr.io/sw-campus/sw-campus-ai:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
