{{- if .Values.configMaps.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.client.configMap.name }}
data:
  {{- if .Values.client.configMap.data }}
  {{- toYaml .Values.client.configMap.data | nindent 2 }}
  {{- else }}
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://softwarecampus.co.kr/api"
  {{- end }}
{{- end }}

