{{- if .Values.client.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sw-campus-client
  labels:
    app: sw-campus-client
spec:
  type: {{ .Values.client.service.type }}
  selector:
    app: sw-campus-client
  ports:
    - name: http
      port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
{{- end }}
