{{- if .Values.configMaps.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.server.configMap.name }}
data:
  {{- $profile := "staging" }}                    # default profile은 staging
  {{- if eq .Values.global.namespace "release" }} # release 환경에서는 prod로 설정
    {{- $profile = "prod" }}
  {{- end }}
  SPRING_PROFILES_ACTIVE: {{ $profile }}
  {{- if .Values.server.configMap.data }}
    {{- range $key, $value := .Values.server.configMap.data }}
    {{- if ne $key "SPRING_PROFILES_ACTIVE" }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
