{{- if .Values.configMaps.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.server.configMap.name }}
data:
  {{- /* profile 결정 */}}
  {{- $profile := "staging" }}
  {{- if eq .Values.global.namespace "release" }}
    {{- $profile = "prod" }}
  {{- end }}

  SPRING_PROFILES_ACTIVE: {{ $profile | quote }}

  {{- /* server.configMap.data 가 있을 때만 주입 */}}
  {{- with .Values.server.configMap.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
