containers:
  - name: server
    image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
    imagePullPolicy: {{ .Values.server.image.pullPolicy }}

    ports:
      - containerPort: 8080
        protocol: TCP

    {{- if .Values.server.resources }}
    resources:
      {{- toYaml .Values.server.resources | nindent 12 }}
    {{- end }}

    envFrom:
      - configMapRef:
          name: { { .Values.server.configMap.name } }

      { { - if .Values.server.secret.enabled } }
      - secretRef:
          name: { { .Values.server.secret.name } }
      { { - end } }

      { { - if .Values.server.awsSecret } }
      - secretRef:
          name: { { .Values.server.awsSecret } }
      { { - end } }

      { { - if .Values.server.dbSecret } }
      - secretRef:
          name: { { .Values.server.dbSecret } }
      { { - end } }

      { { - if .Values.server.oauthSecret } }
      - secretRef:
          name: { { .Values.server.oauthSecret } }
      { { - end } }
