{{- if .Values.configMaps.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.server.configMap.name }}
data:
  {{- $profile := "staging" }}                    # default profile은 staging
  {{- if eq .Values.global.namespace "release" }} # release 환경에서는 prod로 설정
    {{- $profile = "prod" }}
  {{- end }}
  {{- if .Values.server.configMap.data }}
  {{- $data := .Values.server.configMap.data }}
  SPRING_PROFILES_ACTIVE: {{ $profile }}
  {{- range $key, $value := $data }}
  {{- if ne $key "SPRING_PROFILES_ACTIVE" }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
  {{- else }}
  SPRING_PROFILES_ACTIVE: {{ $profile }}
  DB_HOST: {{ .Values.database.externalService.name }}
  DB_PORT: "{{ .Values.database.externalService.port }}"
  {{- end }}
{{- end }}

